### PR TITLE
Allow for SPA apps to take full control of the views they send

### PR DESCRIPTION
**Pull request by cdanea**
By forcing the loaded HTML substrate to be reported ASAP require.js loads the AMD module at whatever URI it was requested there can be duplicates and even zombies reported by mistake.

This change adds a new config value, and also sets the default to 'yes, automatically register a page view on the GoogleAnalytics constructor', just as we used to.

You may choose a better named key name for the config, but this really is appreciated for SPAs

### CODE REVIEW

**Comment by cdanea** [comment]
The Travis build fails miserably. I was unable to make it work. The devDependencies are so old that virtually all are marked as deprecated.

**Comment by metalshark** [comment]
Hi @cdanea the dependencies can definitely be upgraded.

However pardon my ignorance - what is an SPA application and why do they need this charge?

**Comment by metalshark** [comment]
@cdanea I have no problems with adding a config to disable the initial view - however I'd prefer if it was reversed from your implementation (so that you add a flag saying noInitialView: true rather than initialView: true).

**Comment by cdanea** [comment]
ok, I'll change it to be complementary

ps
SPA = Single Page Applications (like Backbone, Marionette, Ember, AngularJS powered web apps)

**Comment by cdanea** [comment]
I'm a bit confused, let me check if I got this correctly. The backwards compatible setting would be 

```
 noInitialView: false
```

With the desired effect of preserving current behavior for other downstream projects of "yes, automatically call view() on page load"

Did I get it right?

**Comment by metalshark** [comment]
I've checked in your fixes - changed the documentation a bit and added a
test:

https://github.com/thomaswelton/requirejs-google-analytics/commits/master

will look to get Travis fixed and then will release an update.

Thank you for this by the way - its always good to add new use cases where
it makes sense.

**Comment by cdanea** [comment]
Looks great, thanks. Reverting our bower to the your upstream!

**Pull request merged**
